// Code generated by build-mobile — DO NOT EDIT.
// Embeds the mobile web frontend (web-mobile/dist/) into the binary.
//
// To regenerate after changing the mobile frontend:
//   cd web-mobile && npm run build && copy dist\* ..\internal\serve\mobileui\dist\

package serve

import (
	"embed"
	"io/fs"
)

//go:embed mobileui/dist
var mobileEmbed embed.FS

//go:embed mobileui/dist/index.html
var mobileIndexHTML []byte

func init() {
	// Override the stub getters from mobile.go
	tryMobileDist = func() (fs.FS, bool) {
		sub, err := fs.Sub(mobileEmbed, "mobileui/dist")
		if err != nil {
			return nil, false
		}
		return sub, true
	}
	getMobileIndex = func() ([]byte, bool) {
		return mobileIndexHTML, true
	}
}
